module.exports = (value) => {
  if (!value) { return ''; }
  if (["UNKNOWN","PDF","POWER_POINT","POWER_POINT_X","POWER_POINT_M","POWER_POINT_T","WORD","WORD_X","WORD_M","WORD_T","PPS","PPSX","EXCEL","EXCEL_X","EXCEL_M","EXCEL_T","GOOGLE_DOCUMENT","GOOGLE_PRESENTATION","GOOGLE_SPREADSHEET","GOOGLE_DRAWING","GOOGLE_FORM","GOOGLE_SCRIPT","LINK","SLIDE","AAC","ACGI","AI","AVI","BMP","BOXNOTE","CSV","EPS","EXE","FLASH","GIF","GZIP","HTM","HTML","HTX","JPEG","JPE","PJP","PJPEG","JFIF","JPG","JS","MHTM","MHTML","MP3","M4A","M4V","MP4","MPEG","MPG","MOV","MSG","ODP","ODS","ODT","OGV","PNG","PSD","RTF","QUIPDOC","SHTM","SHTML","SNOTE","STYPI","SVG","SVGZ","TEXT","THTML","VISIO","WMV","WRF","XML","ZIP","XZIP","WMA","XSN","TRTF","TXML","WEBVIEW","RFC822","ASF","DWG","JAR","XJS","OPX","XPSD","TIF","TIFF","WAV","CSS","THUMB720BY480","THUMB240BY180","THUMB120BY90","ALLTHUMBS","PAGED_FLASH","PACK","C","CPP","WORDT","INI","JAVA","LOG","POWER_POINTT","SQL","XHTML","EXCELT"].indexOf(value) < 0) {
    throw new Error('Invalid FileType value: ' + value);
  }
  return value;
};